[build]
pre_cmd = [
  "bun run dev",
  "templ generate",
  "bunx tailwindcss -i ./src/main.css -o ./dist/tailwind.css"
]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000

# Delay after sending Interrupt signal
kill_delay = 10

include_ext = ["templ", "go", "js", "css"]
exclude_dir = ["postgres", "vendor", "misc", "terraform", "dist", "node_modules"]
exclude_regex = ["_templ\\.go"]

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true
