# fly.toml app configuration file generated for marknotes on 2023-08-26T20:48:56+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "marknotes"
primary_region = "sin"

[build]
  dockerfile="Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 4001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mount]
  source = "marknotes_data"
  destination = "/store"
